title: EIS Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.eis.it/
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 — Jan 2
  down: "#e60000"
  systems:
    - name: Webex Calling
      category: Services
    - name: SIP Trunk
      category: Services
    - name: Partner Portal
      category: Portals
      description: https://portal.eisgroup.it/
  dateFormat: January 2, 2006 at 3:04 PM
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  incidentMaxAgeYears: 6
  logo: /img/eis_rgb-bn_h150.png
  incidentPostsPerPage: 5
  googleAnalytics: UA-00000000-1
  monitorBot: false
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  enableUptimeHistogram: true
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Services
      closed: true
    - name: Portals
    - name: Uncategorized
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
